server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
  datasource:
    password: mysql
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
configs:
    name: testing
    jwtToken: wasuinh